### ISSUE TITLE
composer.json requires unstable package

### ISSUE THREAD

**Issue by marcuswinkler** [mcustiel/phiremock-codeception-module#4]
The package `mcustiel/phiremock-client` is required with a version constraint of `dev-master`. Is there a particular reason for that?

It prevents me from easily installing this package. I don't want to lower my minimum-stability.

```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mcustiel/phiremock-codeception-module ^1.1 -> satisfiable by mcustiel/phiremock-codeception-module[v1.1.0].
    - mcustiel/phiremock-codeception-module v1.1.0 requires mcustiel/phiremock-client dev-master -> found mcustiel/phiremock-client[dev-master] but it does not match your minimum-stability.
```

**Comment by mcustiel** [comment]
Hey @marcuswinkler Thanks for pointing this out. There's no reason for that dev-master other than I forgot it after finishing the development.
I created a PR to fix it. 
Thanks again.

**Comment by marcuswinkler** [comment]
Thanks for fixing so quickly!
