### ISSUE TITLE
Could not find the configured expectations path

### ISSUE THREAD

**Issue by enduro44** [mcustiel/phiremock-codeception-module#7]
Hi!
I got error when running codeception, with phiremock-codeception-module 1.1.2 (with 1.0.2 everything is fine).

In DirectoryPath.php line 68:                                                                                                                       
Could not find the configured expectations path: C:\wamp\www\bta\checkout-server\web\C:\wamp\www\bta\checkout-serve  
  r\web\tests/_data\phiremock-expectations 

Problem is here - https://captureme.tinytake.com/tt/NTA4MzAzMF8xNTk2NzI0Mg
I guess it's Windows specific issue

**Comment by mcustiel** [comment]
Hello @enduro44 
Thanks for debugging it.
I will have a look at the code, but it's not possible for me to test it as I don't have a windows setup. Probably I will come back to you to test it if that's ok.

**Comment by enduro44** [comment]
yeah, ok!

> Hello @enduro44
> Thanks for debugging it.
> I will have a look at the code, but it's not possible for me to test it as I don't have a windows setup. Probably I will come back to you to test it if that's ok.

**Comment by enduro44** [comment]
Thank you @mcustiel now it works on Windows just fine :)
