### ISSUE TITLE
[Error] Call to undefined function on() 

### ISSUE THREAD

**Issue by barsukov2** [mcustiel/phiremock-codeception-module#9]
Hey guys
I want to work with phiremock module in my tests
So, for test - i started phiremock sserver and it works
Next, i create codeception project and install phiremock module as in readme
I create dummy Cest with
```
$I->expectARequestToRemoteServiceWithAResponse(
            on(getRequest()->andUrl(isEqualTo('/some/url')))
                ->then(respond(203)->andBody('I am a response'))
        );
```
And i get
`[Error] Call to undefined function on()`
in terminal

Please help me - what am i doing wrong?

**Comment by mcustiel** [comment]
Hello @barsukov2 
The list of functions you can use is here: https://github.com/mcustiel/phiremock-client/blob/master/src/helper_functions.php

You need to import them first to be able to use them like this:
```
use function Mcustiel\Phiremock\Client\on;
```
Hope this helps you.
Best.
